# TODO create a Makefile that checks for luarocks installation.
# if luarocks not found it will be installed
# then install all dependencies for Pegasus

# Pegasus HTTP Server dependencies
luarocks install luacheck
luarocks install mimetypes
luarocks install luasocket
luarocks install busted
luarocks install luafilesystem
luarocks install lzlib